# Generated by Django 5.1.7 on 2025-03-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradosModel',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(choices=[('PRE_KINDER', 'PRE_KINDER'), ('INCIAL 3', 'INCIAL 3'), ('INCIAL 4', 'INCIAL 4'), ('INCIAL 5', 'INCIAL 5')], max_length=15)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'grados',
            },
        ),
        migrations.CreateModel(
            name='PadreApoderadoModel',
            fields=[
                ('id_padre', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('create_en', models.DateTimeField(auto_now_add=True)),
                ('update_en', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], max_length=10)),
            ],
            options={
                'verbose_name': 'Padre Apoderado',
                'verbose_name_plural': 'Padres Apoderados',
                'db_table': 'padre_apoderado',
            },
        ),
        migrations.CreateModel(
            name='ServiciosModel',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='DocenteModel',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('birthdate', models.DateField()),
                ('create_en', models.DateTimeField(auto_now_add=True)),
                ('update_en', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], max_length=10)),
                ('grade', models.ForeignKey(db_column='id_grado', on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='services.gradosmodel')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='AlumnoModel',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('tipo_alumno', models.CharField(choices=[('REGULAR', 'REGULAR'), ('LIBRE', 'LIBRE')], max_length=15)),
                ('birthdate', models.DateField()),
                ('create_en', models.DateTimeField(auto_now_add=True)),
                ('update_en', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], max_length=10)),
                ('id_grado', models.ForeignKey(db_column='id_grado', on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='services.gradosmodel')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='AlumnoApoderadoModel',
            fields=[
                ('id_alumno_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(choices=[('PADRE', 'PADRE'), ('MADRE', 'MADRE'), ('ABUELO', 'ABUELO'), ('TIO', 'TIO'), ('OTRO', 'OTRO')], max_length=10)),
                ('create_en', models.DateTimeField(auto_now_add=True)),
                ('update_en', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], max_length=10)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='alumno_apoderado', to='services.alumnomodel')),
                ('id_padre', models.ForeignKey(db_column='id_padre', on_delete=django.db.models.deletion.CASCADE, related_name='alumno_apoderado', to='services.padreapoderadomodel')),
            ],
            options={
                'verbose_name': 'Alumno Apoderado',
                'verbose_name_plural': 'Alumnos Apoderados',
                'db_table': 'alumno_apoderado',
            },
        ),
        migrations.CreateModel(
            name='DocenteServicioModel',
            fields=[
                ('id_docente_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, related_name='docente_servicio', to='services.docentemodel')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='docente_servicio', to='services.serviciosmodel')),
            ],
            options={
                'db_table': 'docente_servicio',
            },
        ),
    ]
