# Generated by Django 5.1.7 on 2025-03-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnomodel',
            old_name='lastname',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='alumnomodel',
            old_name='birthdate',
            new_name='fecha_nac',
        ),
        migrations.RenameField(
            model_name='alumnomodel',
            old_name='name',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='docentemodel',
            old_name='lastname',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='docentemodel',
            old_name='name',
            new_name='especialidad',
        ),
        migrations.RenameField(
            model_name='docentemodel',
            old_name='birthdate',
            new_name='fecha_nac',
        ),
        migrations.RenameField(
            model_name='docentemodel',
            old_name='speciality',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='padreapoderadomodel',
            old_name='lastname',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='padreapoderadomodel',
            old_name='name',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='serviciosmodel',
            old_name='description',
            new_name='descripccion',
        ),
        migrations.RenameField(
            model_name='serviciosmodel',
            old_name='duration',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='serviciosmodel',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='serviciosmodel',
            old_name='price',
            new_name='precio',
        ),
    ]
