# Generated by Django 5.1.7 on 2025-03-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_lastname_alumnomodel_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradosmodel',
            name='grado',
            field=models.CharField(choices=[('PRE_KINDER', 'PRE_KINDER'), ('INICIAL 3', 'INICIAL 3'), ('INICIAL 4', 'INICIAL 4'), ('INICIAL 5', 'INICIAL 5')], max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciosmodel',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviciosmodel',
            name='precio',
            field=models.FloatField(),
        ),
    ]
