# Generated by Django 5.1.7 on 2025-03-31 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_gradosmodel_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnomodel',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alumnomodel',
            name='id_padre',
            field=models.ForeignKey(db_column='id_padre', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='padre_apoderado', to='services.padreapoderadomodel'),
            preserve_default=False,
        ),
    ]
