# Generated by Django 5.1.7 on 2025-03-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alumnomodel_direccion_alumnomodel_id_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnomodel',
            name='id_padre',
        ),
    ]
