# Generated by Django 5.1.7 on 2025-03-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_alumnomodel_id_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='padreapoderadomodel',
            name='genero',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
