# Generated by Django 5.1.7 on 2025-03-31 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_padreapoderadomodel_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnomodel',
            name='id_padre',
            field=models.ForeignKey(db_column='id_padre', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='padre_apoderado', to='services.padreapoderadomodel'),
            preserve_default=False,
        ),
    ]
