# Generated by Django 5.1.7 on 2025-03-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('FINISHED', 'FINISHED'), ('RETIRED', 'RETIRED')], max_length=10)),
                ('observacion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='services.alumnomodel')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='services.serviciosmodel')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='PagosModel',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('YAPE', 'YAPE'), ('PLIN', 'PLIN'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=30)),
                ('mes_correspondiente', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SETIEMBRE', 'SETIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=10)),
                ('fecha_pago', models.DateField()),
                ('observacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CANCELADO', 'CANCELADO'), ('PARCIAL', 'PARCIAL'), ('ANULADO', 'ANULADO')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='transactions.matriculamodel')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
