# Generated by Django 5.1.7 on 2025-03-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_matriculamodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculamodel',
            name='estado',
            field=models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('FINISHED', 'FINISHED'), ('RETIRED', 'RETIRED')], default='ACTIVATE', max_length=10),
        ),
    ]
